build_from:
  aarch64: 'ghcr.io/hassio-addons/base:15.0.7'
  amd64: 'ghcr.io/hassio-addons/base:15.0.7'
  armv7: 'ghcr.io/hassio-addons/base:15.0.7'
labels:
  org.opencontainers.image.title: 'RustDesk Server'
  org.opencontainers.image.description: 'Run a RustDesk server for remote desktop connections'
  org.opencontainers.image.source: 'https://github.com/Benicol/rustdesk-addon'
  org.opencontainers.image.vendor: 'Home Assistant Community Add-ons'
  org.opencontainers.image.authors: 'Home Assistant Community'
  org.opencontainers.image.licenses: 'MIT'
args:
  RUSTDESK_VERSION: '1.1.10-3'
