name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * 0'

env:
  DEFAULT_PYTHON: '3.11'

jobs:
  information:
    name: Gather add-on information
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.information.outputs.architectures }}
      build: ${{ steps.information.outputs.build }}
      description: ${{ steps.information.outputs.description }}
      name: ${{ steps.information.outputs.name }}
      slug: ${{ steps.information.outputs.slug }}
      target: ${{ steps.information.outputs.target }}
      version: ${{ steps.information.outputs.version }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run add-on information action
        id: information
        uses: frenck/action-addon-information@v1.4.2
        with:
          path: './rustdesk'

  build:
    name: Build ${{ matrix.architecture }}
    runs-on: ubuntu-latest
    needs: information
    strategy:
      matrix:
        architecture: ${{ fromJson(needs.information.outputs.architectures) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🔧 Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: 🏗 Set up build cache
        id: cache
        uses: actions/cache@v4
        with:
          path: /tmp/.docker-cache
          key: docker-${{ matrix.architecture }}-${{ github.sha }}
          restore-keys: |
            docker-${{ matrix.architecture }}
      - name: 🏗 Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: 🏗 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: ℹ️ Compose build flags
        id: flags
        run: |
          echo "date=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT
          echo "Build information path: ${{ needs.information.outputs.build }}"
          echo "Architecture: ${{ matrix.architecture }}"

          # Debug: show the content of the build file
          if [[ -f "${{ needs.information.outputs.build }}" ]]; then
            echo "Build file content:"
            cat "${{ needs.information.outputs.build }}"
          else
            echo "Build file not found, using direct path"
            cat "./rustdesk/build.yaml"
          fi

          # Try to get the base image
          if [[ -f "${{ needs.information.outputs.build }}" ]]; then
            from=$(yq eval ".build_from.${{ matrix.architecture }}" "${{ needs.information.outputs.build }}")
          else
            from=$(yq eval ".build_from.${{ matrix.architecture }}" "./rustdesk/build.yaml")
          fi

          echo "Base image: ${from}"
          echo "from=${from}" >> $GITHUB_OUTPUT

          if [[ "${{ matrix.architecture}}" = "amd64" ]]; then
            echo "platform=linux/amd64" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.architecture }}" = "armhf" ]]; then
            echo "platform=linux/arm/v6" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.architecture }}" = "armv7" ]]; then
            echo "platform=linux/arm/v7" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.architecture }}" = "aarch64" ]]; then
            echo "platform=linux/arm64/v8" >> $GITHUB_OUTPUT
          else
            echo "::error ::Could not determine platform for architecture ${{ matrix.architecture }}"
            exit 1
          fi
      - name: 🏗 Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 🚀 Build
        uses: docker/build-push-action@v5.1.0
        with:
          build-args: |
            BUILD_ARCH=${{ matrix.architecture }}
            BUILD_DATE=${{ steps.flags.outputs.date }}
            BUILD_DESCRIPTION=${{ needs.information.outputs.description }}
            BUILD_FROM=${{ steps.flags.outputs.from }}
            BUILD_NAME=${{ needs.information.outputs.name }}
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_VERSION=${{ needs.information.outputs.version }}
          context: rustdesk
          file: rustdesk/Dockerfile
          platforms: ${{ steps.flags.outputs.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.architecture }}-addon-rustdesk:${{ needs.information.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.architecture }}-addon-rustdesk:latest
          cache-from: |
            type=local,src=/tmp/.docker-cache
            ghcr.io/${{ github.repository_owner }}/${{ matrix.architecture }}-addon-rustdesk:buildcache
          cache-to: |
            type=local,dest=/tmp/.docker-cache-new,mode=max
            ghcr.io/${{ github.repository_owner }}/${{ matrix.architecture }}-addon-rustdesk:buildcache
      - name: 🚚 Swap build cache
        run: |
          rm -rf /tmp/.docker-cache
          mv /tmp/.docker-cache-new /tmp/.docker-cache
